// This file is automatically generated by qtc from "index.qtpl".
// See https://github.com/valyala/quicktemplate for details.

// Render landing page

//line index.qtpl:4
package templates

//line index.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line index.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line index.qtpl:4
func StreamIndex(qw422016 *qt422016.Writer) {
	//line index.qtpl:4
	qw422016.N().S(`<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="shortcut icon" href="/ass/favicon.ico"><title>R/a/dio</title><link href="/ass/css/base.css" rel="stylesheet">`)
	//line index.qtpl:13
	qw422016.N().S(`<link href="/ass/css/dark.css" rel="stylesheet"></head><body>Hello</body></html>`)
//line index.qtpl:20
}

//line index.qtpl:20
func WriteIndex(qq422016 qtio422016.Writer) {
	//line index.qtpl:20
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line index.qtpl:20
	StreamIndex(qw422016)
	//line index.qtpl:20
	qt422016.ReleaseWriter(qw422016)
//line index.qtpl:20
}

//line index.qtpl:20
func Index() string {
	//line index.qtpl:20
	qb422016 := qt422016.AcquireByteBuffer()
	//line index.qtpl:20
	WriteIndex(qb422016)
	//line index.qtpl:20
	qs422016 := string(qb422016.B)
	//line index.qtpl:20
	qt422016.ReleaseByteBuffer(qb422016)
	//line index.qtpl:20
	return qs422016
//line index.qtpl:20
}
