// This file is automatically generated by qtc from "index.qtpl".
// See https://github.com/valyala/quicktemplate for details.

// Render landing page

//line index.qtpl:4
package templates

//line index.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line index.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line index.qtpl:4
func StreamIndex(qw422016 *qt422016.Writer) {
	//line index.qtpl:4
	qw422016.N().S(`<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="shortcut icon" href="/ass/favicon.ico"><title>R/a/dio</title><link href="/ass/css/base.css" rel="stylesheet">`)
	//line index.qtpl:13
	qw422016.N().S(`<link href="/ass/css/dark.css" rel="stylesheet"></head><body><section id="main" class="flex-column"><section id="top-container" class="flex-row margin"><img class="margin" src="/ass/logo.png" alt="R/a/dio"><div class="margin flex-column"><div class="margin flex-row"><div id="title-volume"><img src="/ass/logo_title.png" alt="R/a/dio" style="width: 100% !important; margin-bottom: 15px;"></div><div class="flex-column"><button class="btn btn-primary btn-block" id="stream-play" style="display: block;">Play Stream</button><div>OPTIONS?</div></div></div><div class="flex-column">`)
	//line index.qtpl:36
	qw422016.N().S(`<b id="now-playing">NOW PLAYING</b><div>PROGRESS</div><span class="flex-row"><span id="listeners" class="flex-center">LISTENERS</span><span id="time-progress" class="flex-center">TIME</span></span></div></div><div class="flex-column margin"><img id="dj-image" src="https://r-a-d.io/api/dj-image/18" style="max-height: 180px"><span id="dj-name">Hanyuu-sama<span></div></section><section class="flex-row"><article class="flex-center"><header>Last Played</header><table id="last-played"></table></article><article class="flex-center"><header>Queue</header><table id="queue"></table></article></section></section></body></html>`)
//line index.qtpl:67
}

//line index.qtpl:67
func WriteIndex(qq422016 qtio422016.Writer) {
	//line index.qtpl:67
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line index.qtpl:67
	StreamIndex(qw422016)
	//line index.qtpl:67
	qt422016.ReleaseWriter(qw422016)
//line index.qtpl:67
}

//line index.qtpl:67
func Index() string {
	//line index.qtpl:67
	qb422016 := qt422016.AcquireByteBuffer()
	//line index.qtpl:67
	WriteIndex(qb422016)
	//line index.qtpl:67
	qs422016 := string(qb422016.B)
	//line index.qtpl:67
	qt422016.ReleaseByteBuffer(qb422016)
	//line index.qtpl:67
	return qs422016
//line index.qtpl:67
}
